# Generated by Django 2.1.5 on 2019-02-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200)),
                ('hotel_ranking', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cities',
            name='city_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='city_id',
            field=models.ForeignKey(on_delete=None, to='places.Cities'),
        ),
    ]
