# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-17 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20190216_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='city_description',
            field=models.CharField(default='any thing', max_length=1500),
        ),
        migrations.AddField(
            model_name='countries',
            name='country_description',
            field=models.CharField(default='any thing', max_length=1500),
        ),
    ]
