# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-18 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20190217_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='city_image',
            field=models.CharField(default='any thing', max_length=200),
        ),
    ]
