# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-18 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_cities_city_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='city_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
