# Generated by Django 2.1.7 on 2019-02-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20190219_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='city',
            new_name='city_id',
        ),
    ]
