# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-18 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20190218_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='city_image',
            field=models.ImageField(blank=True, upload_to='system/static/images'),
        ),
    ]
