# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-18 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20190218_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='city_description',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='countries',
            name='country_description',
            field=models.CharField(max_length=1500),
        ),
    ]
