# Generated by Django 2.1.7 on 2019-02-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20190219_1518'),
        ('places', '0008_auto_20190219_1403'),
    ]

    operations = [
    ]
