# Generated by Django 2.1.7 on 2019-02-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_merge_20190219_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='city_description',
            field=models.CharField(default='text', max_length=1500),
        ),
        migrations.AddField(
            model_name='countries',
            name='country_description',
            field=models.CharField(default='text', max_length=1500),
        ),
    ]
