# Generated by Django 2.1.5 on 2019-02-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0002_remove_rides_from_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='from_location',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rides',
            name='ride_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='rides',
            name='ride_time',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='rides',
            name='to_location',
            field=models.IntegerField(default=0),
        ),
    ]
