# Generated by Django 2.1.5 on 2019-02-20 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0004_auto_20190214_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='user_id',
            field=models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
