# Generated by Django 2.1.5 on 2019-02-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0005_auto_20190220_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='ride_date',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
