# Generated by Django 2.1.5 on 2019-02-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200)),
                ('hotel_ranking', models.IntegerField()),
                ('city_id', models.ForeignKey(on_delete=None, to='places.Cities')),
            ],
        ),
    ]
