# Generated by Django 2.1.5 on 2019-02-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='city_id',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
