# Generated by Django 2.1.5 on 2019-02-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_reservation', '0003_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='from_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='reservations',
            name='to_date',
            field=models.DateField(default=None),
        ),
    ]
