# Generated by Django 2.1.5 on 2019-02-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_reservation', '0005_auto_20190220_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='from_date',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='to_date',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
