# Generated by Django 2.1.5 on 2019-02-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0002_auto_20190213_1420'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_Experiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('city_id', models.ForeignKey(on_delete=None, to='places.Cities')),
                ('user_id', models.ForeignKey(on_delete=None, to='authentication.Users')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='user_experience_id',
            field=models.ForeignKey(on_delete=None, to='blog.User_Experiences'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(on_delete=None, to='authentication.Users'),
        ),
    ]
