# Generated by Django 2.1.7 on 2019-02-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_experiences_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_experiences',
            name='description',
            field=models.CharField(default='text', max_length=1000),
        ),
    ]
