# Generated by Django 2.1.5 on 2019-02-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20190214_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rides',
            name='user',
        ),
        migrations.DeleteModel(
            name='Hotels',
        ),
        migrations.DeleteModel(
            name='Reservations',
        ),
        migrations.DeleteModel(
            name='Rides',
        ),
    ]
