# Generated by Django 2.1.5 on 2019-02-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190214_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_is_blocked',
            field=models.BooleanField(default=0),
        ),
    ]
