# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-19 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_users_user_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='system/static/images/profile'),
        ),
    ]
