# Generated by Django 2.1.7 on 2019-02-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_users_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_image',
            field=models.ImageField(blank=True, default='text', upload_to='system/static/images/profile'),
        ),
    ]
